name: shirokane
version: 0.1.0.0
license: BSD-3-Clause
extra-source-files:
  - README.md

executables:
  shirokane:
    main: Main.hs
    source-dirs: app
    language: GHC2024
    ghc-options:
      - -Wall
    dependencies:
      - base >= 4

library:
  source-dirs: src
  language: GHC2024
  ghc-options:
    - -Wall
  dependencies:
    - base >= 4
